apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{.Values.name}}
  namespace: {{.Values.namespace}}
rules:
  - apiGroups: ["", "apps", "networking.k8s.io"]
    resources:
      [
        "pods",
        "deployments",
        "ingresses",
        "services",
        "statefulsets",
        "secrets",
      ]
    verbs: ["get", "patch", "create", "watch", "list", "delete"]
