apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.namespace }}
kind: RoleBinding 
{{- else }}
kind: ClusterRoleBinding
{{- end }}
metadata:
  name: {{.Values.name}}
{{- if .Values.namespace }}
  namespace: {{.Values.namespace}}
{{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
{{- if .Values.namespace }}
  kind: Role
{{- else }}
  kind: ClusterRole
  name: {{.Values.name}}
{{- end }}
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User 
    name: {{.Values.name}}
