apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name }}
  namespace: {{.Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{.Values.name }}
  template:
    metadata:
      labels:
        app: {{.Values.name }}
    spec:
      containers:
        - name: {{.Values.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag}}
          resources:
            limits:
              memory: "512Mi"
              cpu: "100m"
          ports:
            - containerPort: {{.Values.port }}
          env:
            - name: "APP_PORT"
              value: "{{.Values.port }}"
{{ if .Values.env_secret_name }}
          volumeMounts:
            - mountPath: "/app/.env"
              subPath: ".env"
              name: env-file
              readOnly: true

      volumes:
        - name: env-file
          secret:
            secretName: {{.Values.env_secret_name}}
{{ end }}