{{- if .Values.host -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}-ingress
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    alb.ingress.kubernetes.io/group.name: {{ .Values.alb_group_name }}
spec:
  tls:
    - hosts:
        - {{ .Values.host }}
      secretName: {{ .Values.host }}-tls-secret
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ .Values.name }}
                port:
                  number: {{.Values.port }}
{{- end -}}
